# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_auto_20160801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceusage",
            name="name",
            field=models.CharField(max_length=200, verbose_name="nom"),
        ),
    ]
