# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20161219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='key',
            field=models.CharField(db_index=True, max_length=100, verbose_name='clé'),
        ),
        migrations.AlterIndexTogether(
            name='metadata',
            index_together=set([('key', 'deletion_date')]),
        ),
    ]
