# Generated by Django 2.1.3 on 2018-12-02 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_auto_20181010"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"verbose_name": "historique", "verbose_name_plural": "historiques"},
        ),
        migrations.AlterModelOptions(
            name="historyfield",
            options={
                "verbose_name": "historique de champ modifié",
                "verbose_name_plural": "historiques de champs modifiés",
            },
        ),
        migrations.AddField(
            model_name="historyfield",
            name="editable",
            field=models.BooleanField(default=True, editable=False, verbose_name="éditable"),
        ),
        migrations.AlterField(
            model_name="global",
            name="content_type",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
                verbose_name="type d'entité",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
                verbose_name="type d'entité",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="histories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="historyfield",
            name="history",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="common.History",
                verbose_name="historique",
            ),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
                verbose_name="type d'entité",
            ),
        ),
        migrations.AlterField(
            model_name="serviceusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
    ]
