# Generated by Django 2.1.5 on 2019-01-30 10:27

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20181202'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='collector',
            field=common.fields.JsonField(blank=True, editable=False, null=True, verbose_name='collection'),
        ),
    ]
