# Generated by Django 3.2 on 2021-04-22 00:14

import common.fields
import common.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20190201'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusage',
            name='extra',
            field=common.fields.JsonField(blank=True, decoder=common.utils.JsonDecoder, encoder=common.utils.JsonEncoder, null=True, verbose_name='extra'),
        ),
    ]
