# Generated by Django 5.0 on 2023-12-07 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_auto_20210701"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="history",
            new_name="common_history_gfk_idx",
            old_fields=("content_type", "object_id"),
        ),
        migrations.RenameIndex(
            model_name="metadata",
            new_name="common_metadata_gfk_idx2",
            old_fields=("content_type", "object_id", "deletion_date"),
        ),
        migrations.RenameIndex(
            model_name="metadata",
            new_name="common_metadata_gfk_idx3",
            old_fields=("content_type", "object_id", "deletion_date", "key"),
        ),
        migrations.RenameIndex(
            model_name="metadata",
            new_name="common_metadata_gfk_idx",
            old_fields=("content_type", "object_id"),
        ),
    ]
